"""The fictional sample library. Every title, author, publisher and ISBN is invented."""

def b(slug, title, author, publisher, year, genre, design, pal, desc, series=None, idx=None, subjects=None, lang="en"):
    return dict(slug=slug, title=title, author=author, publisher=publisher, year=year, genre=genre,
                design=design, pal=pal, description=desc, series=series, series_index=idx,
                subjects=subjects or [genre], lang=lang)

BOOKS = [
    b("the-clockwork-cartographer", "The Clockwork Cartographer", "Mira Vance", "Lantern & Vale", 2021, "Science Fiction",
      "gears", ["#3b2a1a", "#120c07", "#d9a651", "#f3e6c8"],
      "In a harbour town where the tide is kept by a machine nobody remembers building, a mapmaker is hired to chart an inland sea that six of the seven existing maps get wrong on purpose.",
      series="The Brass Meridian", idx=1, subjects=["Science Fiction", "Steampunk"]),
    b("the-tin-astronomer", "The Tin Astronomer", "Mira Vance", "Lantern & Vale", 2022, "Science Fiction",
      "gears", ["#1c2733", "#090d12", "#c9a961", "#eef1f5"],
      "The second voyage of the Brass Meridian takes its crew north, to an observatory that has been recording a star nobody else can see.",
      series="The Brass Meridian", idx=2, subjects=["Science Fiction", "Steampunk"]),
    b("a-clockwork-tide", "A Clockwork Tide", "Mira Vance", "Lantern & Vale", 2024, "Science Fiction",
      "gears", ["#2a1f2e", "#0d0910", "#d8b46a", "#f5eee0"],
      "The tide machine stops. What the town does in the seven days before the water comes back is the whole of this book.",
      series="The Brass Meridian", idx=3, subjects=["Science Fiction", "Steampunk"]),
    b("signal-in-the-static", "Signal in the Static", "Devin Marsh", "Helix Editions", 2022, "Science Fiction",
      "planet", ["#05070f", "#141a33", "#3b4d8a", "#a9b8ff"],
      "A relay technician on a dying orbital station hears a voice in the carrier wave that is, impossibly, her own.",
      series="Carrier Wave", idx=1),
    b("echoes-of-the-carrier-wave", "Echoes of the Carrier Wave", "Devin Marsh", "Helix Editions", 2023, "Science Fiction",
      "planet", ["#0a0612", "#2a1140", "#7a3a9a", "#e0b3ff"],
      "The signal has an origin, and the origin has a price. Book two of Carrier Wave.",
      series="Carrier Wave", idx=2),
    b("hollow-engines-bright-sparks", "Hollow Engines, Bright Sparks", "Devin Marsh", "Helix Editions", 2020, "Science Fiction",
      "city", ["#07111a", "#0f2233", "#5ef2d6", "#061019"],
      "Twelve linked stories about the people who keep a city's machines running after the city itself has stopped caring."),
    b("gardens-of-rust-and-salt", "Gardens of Rust and Salt", "Imara Okonkwo", "Obsidian House", 2020, "Fantasy",
      "forest", ["#d7dccf", "#3f5145", "#1c2a22", "#f4f6ee"],
      "A gardener who can grow anything except what she is asked for is summoned to a court that has run out of everything.",
      series="Saltverse", idx=1),
    b("iron-orchids", "Iron Orchids", "Imara Okonkwo", "Obsidian House", 2018, "Fantasy",
      "botanical", ["#f1e8d6", "#2b2a26", "#8b3a3a", "#b8722c"],
      "Three sisters, one greenhouse, and a flower that blooms only for liars."),
    b("the-salt-cathedral", "The Salt Cathedral", "Imara Okonkwo", "Obsidian House", 2022, "Fantasy",
      "forest", ["#e8e2d5", "#6b5a4a", "#2e2419", "#fbf7ef"],
      "Beneath the drowned city a cathedral is still being built. Book two of Saltverse.",
      series="Saltverse", idx=2),
    b("a-field-guide-to-vanishing-things", "A Field Guide to Vanishing Things", "Teodora Brandt", "Paper Lantern", 2018, "Magical Realism",
      "botanical", ["#efe9dc", "#1f2a24", "#5c7d5a", "#c2652d"],
      "An encyclopaedia of small disappearances, arranged alphabetically, from Aunts to Zeal."),
    b("the-lighthouse-at-the-end-of-august", "The Lighthouse at the End of August", "Teodora Brandt", "Paper Lantern", 2021, "Literary Fiction",
      "sea", ["#1b2a4a", "#4a6a9a", "#16304f", "#0b1526"],
      "Every summer the family returns to the lighthouse. This is the summer one of them does not."),
    b("a-theory-of-small-disasters", "A Theory of Small Disasters", "Lucas Renner", "Meridian Books", 2020, "Contemporary",
      "minimal", ["#f4f1ea", "#22211f", "#d9482b", "#cfc7b8"],
      "A structural engineer who inspects bridges for a living cannot find the crack in his own marriage."),
    b("quiet-engines", "Quiet Engines", "Lucas Renner", "Meridian Books", 2023, "Thriller",
      "typo", ["#101010", "#f2f2f2", "#e63946", "#000000"],
      "Somebody is switching off the machines that keep a country running, one at a time, in alphabetical order."),
    b("the-last-honest-map", "The Last Honest Map", "Lucas Renner", "Meridian Books", 2025, "Thriller",
      "city", ["#0b0b12", "#1d1a2e", "#ffb347", "#0a0910"],
      "A cartographer for a mapping company finds a street that exists on paper and nowhere else."),
    b("constellations-for-the-sleepless", "Constellations for the Sleepless", "Carmen Dalisay", "Tideline", 2023, "Poetry",
      "constellation", ["#1f2a4d", "#060814", "#e8ecff", "#7f8fd6"],
      "Forty-one poems written between two and five in the morning."),
    b("letters-to-a-drowning-city", "Letters to a Drowning City", "Carmen Dalisay", "Tideline", 2021, "Poetry",
      "letters", ["#2f4858", "#f2e9d8", "#5c8a9a", "#1b2b36"],
      "A sequence of unsent letters to a city that floods a little more each year."),
    b("maps-of-the-unbuilt", "Maps of the Unbuilt", "Yusuf Karim", "Compass & Quill", 2023, "Adventure",
      "map", ["#efe4c8", "#2c2416", "#7fa5b8", "#b23a2b"],
      "An expedition to survey the cities that were planned, funded, and never begun."),
    b("the-cartographers-daughter", "The Cartographer's Daughter", "Yusuf Karim", "Compass & Quill", 2020, "Historical Fiction",
      "deco", ["#0f1f3d", "#d4af5a", "#f6efdc", "#060d1c"],
      "Alexandria, 1923. A young woman inherits her father's maps and the enemies that come with them."),
    b("mercury-in-the-blood", "Mercury in the Blood", "Yusuf Karim", "Compass & Quill", 2018, "Historical Fiction",
      "deco", ["#3a1d0f", "#e0b768", "#f8efe0", "#1c0d05"],
      "A silversmith's apprentice in Ottoman Istanbul learns why the guild never speaks of its founder."),
    b("the-winter-orchard", "The Winter Orchard", "Nils Hagström", "Northlight Press", 2019, "Literary Fiction",
      "mountains", ["#2b3a55", "#c47a5a", "#f7d9a8", "#1e2233"],
      "Three generations of a family who grow apples where apples should not grow."),
    b("what-the-river-kept", "What the River Kept", "Nils Hagström", "Northlight Press", 2022, "Literary Fiction",
      "sea", ["#243b3f", "#6f9aa0", "#1e3538", "#0e1c1e"],
      "A river gives back, thirty years late, the things a village dropped in it."),
    b("the-glass-arithmetic", "The Glass Arithmetic", "Priya Raman", "Helix Editions", 2024, "Science Fiction",
      "constellation", ["#0e2a2a", "#03100f", "#dff7f0", "#3fa08a"],
      "A mathematician discovers that a proof, once written down, changes the thing it describes."),
    b("small-hours", "Small Hours", "Priya Raman", "Meridian Books", 2021, "Contemporary",
      "minimal", ["#ece7e1", "#2a2624", "#2f6f8f", "#d9d1c7"],
      "A night nurse, a night baker and a night bus driver share a city nobody else is awake to see."),
    b("the-orchard-of-lost-keys", "The Orchard of Lost Keys", "Teodora Brandt", "Paper Lantern", 2024, "Magical Realism",
      "mountains", ["#4a2f5c", "#e07b5f", "#ffe0a8", "#2a1a35"],
      "Every key ever lost ends up in the same orchard. A locksmith goes looking for one in particular."),
]

# Original chapter text for the book that appears in the reader screenshot.
CHAPTERS = {
    "the-clockwork-cartographer": [
        ("Chapter One", [
            "The harbour had been quiet for three days, which everyone agreed was a bad sign.",
            "Ilse Marren had learned to read the town the way she read a coastline: by what was missing. No gulls on the breakwater. No boys on the slipway pretending to mend nets. The bell on the customs house had not rung since Tuesday, and nobody had climbed up to find out why.",
            "She unrolled the chart across the table and weighted its corners with brass instruments, each one warm from her pocket. The inland sea lay across the paper in seven different hands, and six of them were wrong on purpose. That was the commission. Not to draw the sea, which had been drawn, but to find out which of the drawings had been paid to lie.",
            "Somewhere below the floorboards the tide machine turned over, patient as a sleeping animal, counting out the hours nobody had asked it to keep. It had been built before the town had a name. It would, the harbourmaster liked to say, be running long after the town had lost it again.",
            "“You drew this from memory?” Aurelio asked. He had come in without knocking, which he did when he wanted to seem unhurried.",
            "“From three memories,” she said. “None of them mine.”",
            "He looked at the chart for a long time. He had the face of a man reading a letter addressed to somebody else.",
            "“The channel is wrong,” he said at last.",
            "“The channel is wrong on all seven. That is how I know it is right.”",
            "By morning the fog had drawn its grey wool over the whole town, and the gulls, wherever they had been, came back to argue about it from the rooftops. Ilse packed the instruments in the order she always packed them: dividers, rule, the small brass key that fit no lock she had ever found. Then she went down to look at the machine.",
            "The stairs to the tide room had been cut for shorter people, or for people in less of a hurry. She counted them, as she counted everything, and arrived at the bottom with the number forty-one and no idea what to do with it.",
            "The harbourmaster was already there, which she had not expected, holding a lamp he did not need. The room had its own light. It came from nowhere she could point to and it had the colour of very old paper.",
            "\u201cYou will want to know who paid for the maps,\u201d he said. \u201cEveryone does. It is the wrong question.\u201d",
            "\u201cThen what is the right one?\u201d",
            "\u201cWhy anybody would want to hide a sea.\u201d He set the lamp down on the grating, where its light fell through and was lost. \u201cA sea is a large thing to hide. You would need a great many people to agree not to see it.\u201d",
            "Ilse thought of the six wrong maps, each wrong in its own careful way, and of the seventh, which was hers, and which she had drawn from three memories that were not her own. She thought about how much easier it is to agree not to see something than to agree on what is there.",
            "\u201cThe channel,\u201d she said. \u201cThe one they all get wrong. Where does it go?\u201d",
            "The harbourmaster looked at the machine, and for a moment she thought he was going to answer it instead of her.",
            "\u201cHome,\u201d he said. \u201cIt goes home.\u201d",
        ]),
        ("Chapter Two", [
            "The tide machine lived in a room that had been dug, not built. Its walls sweated. Its floor was a grating over dark water, and the water moved in a way that had nothing to do with the sea outside.",
            "There were, she had been told, only seven true maps of the inland sea, and six of them were wrong on purpose. Nobody had told her who had said so first, and she was beginning to suspect it was the machine.",
            "It was larger than she remembered. Most things were smaller. A great flywheel turned so slowly that she had to watch a single rivet to be sure it moved at all, and around it, in rings, the smaller wheels kept their own faster time, ticking against each other like a roomful of clocks that had agreed to disagree.",
            "“It was not made here,” the harbourmaster said from the doorway. He never came further in. “It was found. The town was built around the finding.”",
            "“Who found it?”",
            "“Someone with a map,” he said, and went back up the stairs.",
            "The brass key fit the lock the way a remembered word fits a sentence: suddenly, and as if it had always belonged. Behind the panel was a second chart, older than any of the seven, and on it the inland sea had no coastline at all. Only a spiral, and a date, and a single word in a hand she knew, because it was hers.",
        ]),
        ("Chapter Three", [
            "Aurelio said the word was a place. The harbourmaster said it was a warning. Ilse, who had written it and could not remember doing so, said nothing for two days and then hired a boat.",
            "The channel that was wrong on all seven maps turned out to be right on the eighth, which was the one she drew as they went, with the boat's compass swinging and the boy at the tiller pretending not to be afraid.",
            "The fog thinned. The water changed colour. And somewhere behind them, faint across the miles, the tide machine rang the customs house bell for the first time since Tuesday.",
        ]),
    ],
}

GENERIC = [
    ("Chapter One", [
        "It began, as these things do, with a letter that arrived a week after the person who wrote it had stopped expecting an answer.",
        "The house was the last on the road and the road was the last in the valley, and beyond it the ground rose into a shoulder of pine that kept the snow late into April. From the kitchen window you could see the whole of the settled world and none of the rest.",
        "She read the letter twice standing up and a third time sitting down, which was how she knew it mattered.",
        "“Well,” said her brother, who had read it over her shoulder and was already putting on his coat. “We had better go and see.”",
    ]),
    ("Chapter Two", [
        "The town had one street and had made the most of it. Everything a person could need was on the left-hand side, and everything they could want was on the right, and the two sides had not spoken since the war.",
        "They found the address without difficulty. Finding the door took longer.",
        "Inside, someone had been waiting a long time, and had arranged the chairs to say so.",
    ]),
]
