#!/bin/bash
# Self-host the Cormorant Garamond webfont.
#
# WHY THIS EXISTS: the app shell used to pull this font from
# fonts.googleapis.com via a render-blocking <link> in <head>. On a LAN /
# Tailscale client with no fast route to the public internet (e.g. an iPad
# home-screen launch), that external request stalled first paint for ~60s —
# the whole page was blank until iOS Safari's resource timeout fired. Baking
# the woff2 into the image removes the external dependency: the font is served
# same-origin from /static/fonts and first paint never waits on Google.
#
# The font is used in exactly one decorative spot (.series-name). If this
# script is skipped or its download fails, the CSS falls back to Georgia and
# the app is fully functional — so a font fetch must NEVER break the build.
#
# Run from the repo root (Docker: /app, after `COPY . .`). It (re)generates
# app/static/fonts/cormorant.css + the woff2 files it references. A committed
# copy of those files lives in the repo as a vendored fallback, so an
# internet-less build still ships a working font.
set -uo pipefail

FONT_DIR="${1:-app/static/fonts}"

python3 - "$FONT_DIR" <<'PY' || echo "fonts: refresh failed — keeping vendored copy (Georgia fallback if absent)"
import os, re, sys, tempfile, shutil, urllib.request

font_dir = sys.argv[1]
os.makedirs(font_dir, exist_ok=True)

CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Cormorant+Garamond:ital,wght@1,400;1,500&display=swap")
# A full desktop Chrome UA makes Google return woff2 (smallest modern format)
# rather than ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


print("fonts: fetching @font-face CSS from Google")
css = fetch(CSS_URL)

# Build everything in a temp dir first; only swap into place once every woff2
# downloaded, so a mid-way failure never leaves a half-written font set.
tmp = tempfile.mkdtemp()
seen = {}


def repl(m):
    url = m.group(1)
    if url not in seen:
        fname = "cormorant-garamond-%d.woff2" % len(seen)
        print("fonts: downloading %s" % fname)
        with open(os.path.join(tmp, fname), "wb") as fh:
            fh.write(fetch(url, binary=True))
        seen[url] = fname
    # url() is rewritten to the served same-origin path.
    return "url(/static/fonts/%s)" % seen[url]


local_css = re.sub(r"url\((https://[^)]+\.woff2)\)", repl, css)
if not seen:
    raise SystemExit("fonts: no woff2 URLs found in CSS — aborting")

with open(os.path.join(tmp, "cormorant.css"), "w", encoding="utf-8") as fh:
    fh.write("/* Generated by tools/install_fonts.sh — do not edit by hand. */\n")
    fh.write(local_css)

for name in os.listdir(tmp):
    shutil.move(os.path.join(tmp, name), os.path.join(font_dir, name))
shutil.rmtree(tmp, ignore_errors=True)
print("fonts: wrote cormorant.css + %d woff2 file(s) to %s" % (len(seen), font_dir))
PY
